# Tissot
obj-$(CONFIG_FINGERPRINT_GOODIX_GF3208_TISSOT) += goodix_tissot/
obj-$(CONFIG_FINGERPRINT_FPC1020_TISSOT) += fpc_tissot/

# daisy/sakura
obj-$(CONFIG_FINGERPRINT_GOODIX_GF3208_SAKURA) += goodix_sakura/
obj-$(CONFIG_FINGERPRINT_FPC1020_SAKURA) += fpc_sakura/

